name: Generate Latest Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate runner.py
        run: |
          python release.py

      - name: Commit and push runner.py
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add runner.py
          git commit -m "🤖 Auto-generate latest runner.py from ${{ github.sha }}" || echo "No changes to commit"
          git push origin main
