name: Generate Latest Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate runner.py
        run: |
          python release.py

      - name: Upload runner.py as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: runner-latest
          path: runner.py
          retention-days: 30
