name: Release Standalone Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate runner.py
        run: |
          python release.py

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Standalone Runner
          body: |
            ## Latest Standalone Runner

            This is the latest standalone version of the Zysys API Test Framework.

            ### Usage
            ```bash
            # Download and run directly
            curl -L https://github.com/${{ github.repository }}/releases/latest/download/runner.py -o runner.py
            python3 runner.py --help

            # Or use with your test config
            python3 runner.py --config your-tests.yaml
            ```

            ### Features
            - Complete API testing framework in a single file
            - Extension system support
            - Async/await with retry logic
            - Built-in validation and reporting

            ### Version
            Generated from commit: ${{ github.sha }}
            Date: ${{ github.event.head_commit.timestamp }}
          files: runner.py
          draft: false
          prerelease: false

      - name: Create Latest Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -f latest
          git push origin latest --force
